from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('take-attendance/', views.take_attendance_setup, name='take_attendance_setup'),
    path('tracking/', views.database_tracking, name='database_tracking'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('start-session/', views.start_attendance_session, name='start_attendance_session'),
    path('camera/<int:session_id>/', views.live_camera, name='live_camera'),
    path('video_feed/<int:session_id>/', views.video_feed, name='video_feed'),
    path('status-ajax/<int:session_id>/', views.attendance_status_ajax, name='attendance_status_ajax'),
    path('toggle-status/<int:log_id>/', views.toggle_attendance_status, name='toggle_attendance_status'),
    path('mark-all-present/<int:session_id>/', views.mark_all_present, name='mark_all_present'),
    path('reset-session/<int:session_id>/', views.reset_session_attendance, name='reset_session'),
    path('simulate-recognition/<int:session_id>/', views.simulate_recognition_ajax, name='simulate_recognition_ajax'),
    path('export-excel/<int:session_id>/', views.export_session_excel, name='export_excel'),
    path('students/', views.manage_students, name='manage_students'),
    path('add-student/', views.add_student, name='add_student'),
    path('update-student/<int:student_id>/', views.update_student, name='update_student'),
    path('delete-student/<int:student_id>/', views.delete_student, name='delete_student'),
    path('reports/', views.reports_page, name='reports'),
    path('delete-session/<int:session_id>/', views.delete_session, name='delete_session'),
    path('recycle-bin/', views.recycle_bin, name='recycle_bin'),
    path('restore-session/<int:session_id>/', views.restore_session, name='restore_session'),
    path('delete-session-permanently/<int:session_id>/', views.delete_session_permanently, name='delete_session_permanently'),
    path('student-status/<int:student_id>/', views.student_encoding_status, name='student_encoding_status'),
    path('system-stats/', views.system_stats_api, name='system_stats_api'),
    path('sessions-by-date/', views.sessions_by_date_api, name='sessions_by_date_api'),
    path('recognize-frame/<int:session_id>/', views.recognize_frame_ajax, name='recognize_frame_ajax'),
    path('calendar/', views.calendar_page, name='calendar_page'),
    path('session/<int:session_id>/', views.session_detail, name='session_detail'),
    path('session/<int:session_id>/broadcast-email/', views.broadcast_absentee_email, name='broadcast_absentee_email'),
    path('session/<int:session_id>/broadcast-all-email/', views.broadcast_all_email, name='broadcast_all_email'),
    path('session/<int:session_id>/student/<int:student_id>/email/', views.send_single_email, name='send_single_email'),
    path('student/<int:student_id>/update-email/', views.update_student_email_ajax, name='update_student_email_ajax'),
    path('email-preview/<str:filename>/', views.email_preview_view, name='email_preview'),
    path('sms-preview/<str:filename>/', views.sms_preview_view, name='sms_preview'),
    
    # Exam Scanner Routes
    path('exams/', views.exam_list, name='exam_list'),
    path('exams/<int:exam_id>/scanner/', views.exam_scanner, name='exam_scanner'),
    path('exams/<int:exam_id>/recognize-frame/', views.recognize_exam_frame_ajax, name='recognize_exam_frame_ajax'),
    path('exams/<int:exam_id>/report/', views.exam_report, name='exam_report'),
    path('exams/<int:exam_id>/status-ajax/', views.exam_status_ajax, name='exam_status_ajax'),
    path('exams/<int:exam_id>/reset/', views.reset_exam_verification, name='reset_exam_verification'),
    path('exams/<int:exam_id>/complete/', views.complete_exam, name='complete_exam'),
    path('exams/toggle-status/<int:log_id>/', views.toggle_exam_status, name='toggle_exam_status'),
]

