# Generated by Django 5.0.6 on 2026-06-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('roll_number', models.CharField(blank=True, help_text='Roll number of the student.', max_length=50, null=True)),
                ('department', models.CharField(blank=True, help_text='Department, e.g. CSE, MECH, ECE.', max_length=100, null=True)),
                ('section', models.CharField(blank=True, help_text='Section, e.g. A, B, I, N.', max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='students/')),
                ('encoding', models.TextField(blank=True, help_text='512-dimensional face encoding vector stored as a JSON array of floats.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Absent', help_text='Present or Absent', max_length=20)),
                ('time_marked', models.CharField(default='-', help_text='Time marked Present, or - if Absent', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Face recognition confidence percentage')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='attendance.student')),
            ],
            options={
                'ordering': ['student__name'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
