# Generated by Django 5.0.6 on 2026-06-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_facultyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='processing_status',
            field=models.TextField(blank=True, default='{"step": 0, "text": "Queued for processing...", "percent": 5}', help_text='JSON representation of current background processing status.', null=True),
        ),
    ]
