# Generated by Django 5.0.6 on 2026-06-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
