# Generated by Django 5.0.6 on 2026-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
