# Generated by Django 5.0.6 on 2026-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancelog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent contact phone number.', max_length=20, null=True),
        ),
    ]
