# Generated by Django 5.0.6 on 2026-06-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_student_parent_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Parent contact email address.', max_length=254, null=True),
        ),
    ]
