# Generated by Django 5.0.6 on 2026-07-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_student_parent_phone_student_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent contact phone number.', max_length=20, null=True),
        ),
    ]
